{% set version = "1.1.1" %}

#NB: get sha256 from https://pypi.org/project/simple-build-dgcode/#files

package:
  name: simple-build-dgcode
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/simple-build-dgcode/simple-build-dgcode-{{ version }}.tar.gz
  sha256: cbeec2135b5798a08163b8f10ab9db93ace9185e05307fb130600ab315fc8881

build:
  noarch: python
  script: python -m pip install --no-deps -vv .
  number: 1
  entry_points:
    - dgcode_newsimproject = simplebuild_dgcode._cli:newsimproject

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-git-versioning
    - setuptools
  run:
    - python >=3.8
    - simple-build-system >=1.1.0

test:
  requires:
    # Note: The actual tests are defined in run_test.sh
    - c-compiler
    - cxx-compiler
    - pip
    - geant4 >=11.0.0
    - ncrystal

about:
  home: https://mctools.github.io/simplebuild-dgcode
  summary: A very simple to use build system for scientific projects with C++/Python.
  description: |
    A set of simplebuild packages implementing "dgcode", a Geant4-based
    simulation framework. It is primarily intended for usage for simulation of
    thermal neutron detectors and related projects, and it originated in the
    Detector Group at the European Spallation Source ERIC.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://mctools.github.io/simplebuild-dgcode
  dev_url: https://github.com/mctools/simplebuild-dgcode

extra:
  recipe-maintainers:
    - tkittel
